# Cloudflare Worker + D1 SQLite Database
# wrangler.toml configuration file

name = "rsvp-backend"
main = "src/index.js"
compatibility_date = "2023-10-30"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "rsvp-database"
database_id = "YOUR_DATABASE_ID_HERE"  # Replace with actual ID after creating D1 database

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

# Worker configuration
[build]
command = ""

# Routes (optional - for custom domains)
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"